# Generated by Django 5.0 on 2023-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='price',
            field=models.IntegerField(),
        ),
    ]
